#!/usr/bin/env python3
"""Convert cobertura coverage.xml to Sonar Generic Test Coverage XML.

SonarCloud's Cobertura sensor for Python silently drops all hits on
this project (parses ``coverage.xml`` in <250ms and applies 0% coverage)
even after fixing the ``<source>`` element to point at the repo root.
The Sonar Generic Test Coverage format uses ``path`` attributes that map
1:1 against indexed source files, so emitting it directly bypasses
whatever path resolution issue the Cobertura sensor has.

We use ``defusedxml`` rather than the stdlib ``xml`` module so the
parser is hardened against XXE attacks (CWE-611). The cobertura XML we
read is generated by our own pytest-cov run on trusted source, but
``defusedxml`` is a strict drop-in replacement and the safer default.

Format reference:
    https://docs.sonarsource.com/sonarqube/latest/analyzing-source-code/test-coverage/generic-test-data/
"""
from __future__ import annotations

import argparse
from collections import defaultdict
from pathlib import Path

from defusedxml import ElementTree as ET


def _quoteattr(value: str) -> str:
    """Escape and quote an XML attribute value.

    Local equivalent of ``xml.sax.saxutils.quoteattr`` so this script can
    keep the entire xml subsystem on ``defusedxml`` (Semgrep
    ``use-defused-xml``). Only escapes attribute-significant characters;
    never parses XML, so it has no XXE surface.
    """
    escaped = (
        value.replace("&", "&amp;").replace("<", "&lt;").replace('"', "&quot;")
    )
    return f'"{escaped}"'


def parse_args() -> argparse.Namespace:
    """Parse CLI arguments."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--in",
        dest="in_path",
        required=True,
        help="Input cobertura coverage.xml path",
    )
    parser.add_argument(
        "--out",
        dest="out_path",
        required=True,
        help="Output Sonar Generic Test Coverage XML path",
    )
    return parser.parse_args()


def collect_lines(in_path: Path) -> dict[str, dict[int, tuple[int, int, int]]]:
    """Parse cobertura XML, return per-file/line (hits, branches, covered)."""
    by_file: dict[str, dict[int, tuple[int, int, int]]] = defaultdict(dict)
    tree = ET.parse(str(in_path))
    root = tree.getroot()
    for cls in root.iter("class"):
        filename = cls.get("filename", "")
        if not filename:
            continue
        for line in cls.iter("line"):
            number = int(line.get("number", 0))
            hits = int(line.get("hits", 0))
            branch = line.get("branch", "false") == "true"
            condition_coverage = line.get("condition-coverage", "")
            if branch and "(" in condition_coverage:
                # e.g. "50% (1/2)"
                fraction = condition_coverage.split("(")[1].rstrip(")")
                covered, total = fraction.split("/")
                branches_to_cover = int(total)
                covered_branches = int(covered)
            else:
                branches_to_cover = 0
                covered_branches = 0
            by_file[filename][number] = (hits, branches_to_cover, covered_branches)
    return by_file


def emit_xml(
    by_file: dict[str, dict[int, tuple[int, int, int]]],
    out_path: Path,
) -> int:
    """Emit Sonar Generic Test Coverage XML and return file count."""
    out: list[str] = ['<coverage version="1">']
    for file_path in sorted(by_file):
        out.append(f"  <file path={_quoteattr(file_path)}>")
        for ln in sorted(by_file[file_path]):
            hits, b_total, b_covered = by_file[file_path][ln]
            covered = "true" if hits > 0 else "false"
            attrs = f'lineNumber="{ln}" covered="{covered}"'
            if b_total > 0:
                attrs += f' branchesToCover="{b_total}" coveredBranches="{b_covered}"'
            out.append(f"    <lineToCover {attrs}/>")
        out.append("  </file>")
    out.append("</coverage>")
    out.append("")
    out_path.write_text("\n".join(out), encoding="utf-8")
    return len(by_file)


def summarise(by_file: dict[str, dict[int, tuple[int, int, int]]]) -> tuple[int, int]:
    """Return total / covered line counts."""
    total = sum(len(v) for v in by_file.values())
    covered = sum(
        sum(1 for hits, _, _ in v.values() if hits > 0) for v in by_file.values()
    )
    return total, covered


def main() -> int:
    """CLI entry point."""
    args = parse_args()
    in_path = Path(args.in_path)
    out_path = Path(args.out_path)
    by_file = collect_lines(in_path)
    file_count = emit_xml(by_file, out_path)
    total, covered = summarise(by_file)
    print(
        f"Wrote {out_path}: {file_count} files, "
        f"lines {covered}/{total}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
